version: "3.7"

services:
  #  backend:
  #    build:
  #      context: .
  #      dockerfile: deploy/docker/backend/Dockerfile
  #    image: ceramic-go/backend:latest
  #    restart: unless-stopped
  #    command: >
  #      sh -c "python manage.py collectstatic --noinput &&
  #             python manage.py migrate &&
  #             python manage.py runserver 0.0.0.0:8000"
  #    ports:
  #      - "8000:8000"
  #    depends_on:
  #      - db
  #    env_file:
  #      - .env
  #    volumes:
  #      - backend_data:/src
  #      - backend_logs:/src/logs
  #      - backend_static:/src/static
  #      - backend_media:/src/media

  db:
    build:
      context: .
      dockerfile: deploy/docker/postgres/Dockerfile
    image: ceramic-go/postgres:latest
    restart: unless-stopped
    volumes:
      - ceramic_go_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  ceramic_go_db_data:
  redis_data: