version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend/Dockerfile
    image: ceramic-go/backend:latest
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn core.wsgi -b 0.0.0.0:8000 --reload"
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - backend_static:/src/static
      - backend_media:/src/media
      - backend_logs:/src/logs
    cap_add:
      - ALL

  db:
    build:
      context: .
      dockerfile: deploy/docker/postgres/Dockerfile
    image: ceramic-go/db:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432

  redis:
    build:
      context: .
      dockerfile: deploy/docker/redis/Dockerfile
    image: ceramic-go/redis:latest
    restart: unless-stopped
    privileged: true
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
      - redis_conf:/conf
    expose:
      - 6379

volumes:
  db_data:
  redis_data:
  redis_conf:
  backend_static:
  backend_logs:
  backend_media:
