# Generated by Django 5.1.6 on 2025-02-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=0)),
                ('operation_type', models.CharField(choices=[('receipt', 'Поступление'), ('sale', 'Продажа'), ('defect', 'Брак')], db_index=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_operations', to='products.product')),
            ],
            options={
                'verbose_name': 'Учет товара',
                'verbose_name_plural': 'Учет товаров',
                'db_table': 'product_entry_exit',
            },
        ),
    ]
