# Generated by Django 5.1.6 on 2025-02-23 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventoryoperation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Учет товара', 'verbose_name_plural': 'Учет товаров'},
        ),
        migrations.AddField(
            model_name='productinventoryoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinventoryoperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
