# Generated by Django 5.1.6 on 2025-02-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productinventoryoperation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='count',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='operation_type',
            field=models.CharField(choices=[('receipt', 'Поступление'), ('sale', 'Продажа'), ('defect', 'Брак')], db_index=True, max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_operations', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productinventoryoperation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_operations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
