# Generated by Django 5.1.6 on 2025-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventoryoperation',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
